import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createGameServer} from '../backend/server.mjs';
import {emptySave} from '../world-expansion/modules/saveSchema.mjs';
async function boot(options={}){const server=createGameServer({dbPath:':memory:',...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;return {server,origin,close:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));},async request(path,{method='GET',cookie='',body,origin:requestOrigin=origin}={}){const r=await fetch(origin+path,{method,headers:{Origin:requestOrigin,'Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});const result={status:r.status,cookie:r.headers.get('set-cookie'),type:r.headers.get('content-type')};result.body=result.type?.includes('json')?await r.json():await r.text();return result;}};}
async function session(s){const r=await s.request('/api/session',{method:'POST',body:{}});assert.equal(r.status,200);assert.match(r.cookie,/HttpOnly/);assert.match(r.cookie,/SameSite=Strict/);return r.cookie.split(';')[0];}
test('sessions isolate saves; unauthenticated, cross-origin and invalid uploads are rejected',async()=>{const s=await boot();try{assert.equal((await s.request('/api/save')).status,401);assert.equal((await s.request('/api/session',{method:'POST',origin:'https://evil.example',body:{}})).status,403);const a=await session(s),b=await session(s);const v=emptySave();v.profile.scales=42;assert.equal((await s.request('/api/save',{method:'PUT',cookie:a,body:{revision:0,save:v}})).status,200);assert.equal((await s.request('/api/save',{cookie:b})).body.save,null);assert.equal((await s.request('/api/save',{cookie:a})).body.save.profile.scales,42);v.profile.scales=-1;assert.equal((await s.request('/api/save',{method:'PUT',cookie:a,body:{revision:1,save:v}})).status,422);assert.equal((await s.request('/api/save/history/1',{cookie:b})).status,404);}finally{await s.close();}});
test('concurrent writes use compare-and-swap and retain only ten revisions',async()=>{const s=await boot();try{const cookie=await session(s);const saves=await Promise.all([1,2].map(n=>{const v=emptySave();v.profile.scales=n;return s.request('/api/save',{method:'PUT',cookie,body:{revision:0,save:v}});}));assert.deepEqual(saves.map(x=>x.status).sort(),[200,409]);for(let revision=1;revision<12;revision++)assert.equal((await s.request('/api/save',{method:'PUT',cookie,body:{revision,save:emptySave()}})).status,200);const history=(await s.request('/api/save/history',{cookie})).body.versions;assert.equal(history.length,10);assert.equal(history[0].revision,12);assert.equal((await s.request('/api/save/history/1',{cookie})).status,404);}finally{await s.close();}});
test('SQLite preserves sessions and saves after a server restart',async()=>{const dir=await mkdtemp(join(tmpdir(),'gv-test-')),dbPath=join(dir,'save.sqlite');let s=await boot({dbPath});try{const cookie=await session(s),v=emptySave();v.profile.storyCompleted=true;await s.request('/api/save',{method:'PUT',cookie,body:{revision:0,save:v}});await s.close();s=await boot({dbPath});const r=await s.request('/api/save',{cookie});assert.equal(r.body.save.profile.storyCompleted,true);assert.equal(r.body.revision,1);}finally{await s.close();await rm(dir,{recursive:true,force:true});}});
test('static serving exposes game assets but not backend code, database, or git metadata',async()=>{const s=await boot();try{for(const path of ['/.git/config','/.runtime/saves.sqlite','/backend/server.mjs','/package.json','/world-expansion/%2e%2e/backend/server.mjs'])assert.equal((await s.request(path)).status,404,path);assert.equal((await s.request('/')).status,200);assert.equal((await s.request('/world-expansion/modules/saveSchema.mjs')).type,'text/javascript');assert.equal((await s.request('/api/health')).body.service,'galevein-save');}finally{await s.close();}});
test('payload cap and API rate limit are enforced',async()=>{const s=await boot({rateLimit:6});try{const cookie=await session(s);assert.equal((await s.request('/api/save',{method:'PUT',cookie,body:{padding:'x'.repeat(140000)}})).status,413);for(let i=0;i<4;i++)await s.request('/api/health');const r=await s.request('/api/health');assert.equal(r.status,429);}finally{await s.close();}});
