import test from 'node:test';
import assert from 'node:assert/strict';
import {emptySave,validateSave} from '../world-expansion/modules/saveSchema.mjs';
import {SaveStore,SaveConflict,SAVE_KEY,BACKUP_KEY,encodeSave,decodeSave,checksum} from '../world-expansion/modules/saveStore.mjs';
import {SaveSync} from '../world-expansion/modules/saveSync.mjs';
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),map};};
export function fixture(){const save=emptySave();save.profile.scales=26;save.profile.upgrades.rudder=2;save.profile.highestChapter=2;save.checkpoint={mode:'story',rig:'stormcrest',savedAt:1,worldTime:55,flightTime:50,day:.2,state:{hp:89,tutDone:true},loadout:{scales:26,upgrades:{...save.profile.upgrades}},dragon:{position:[12,60,-240],yaw:1,pitch:.2,roll:.1,speed:32},rings:Array.from({length:12},(_,i)=>i<4),tutorial:[true,true,true],gates:[false,false,false],towers:[{hp:0,destroyed:true},{hp:6,destroyed:false}],raid:{on:true,wave:2,hearth:82,riders:[{position:[20,66,-270],hp:1.6,yaw:.5,speed:34,fireCd:-1,diveCd:3,orbit:2}]}};return validateSave(save);}
test('flight, loadout, damaged towers and second-wave raid survive export/import',()=>{const s=new SaveStore(memory());s.save(fixture());const imported=new SaveStore(memory());imported.import(s.export());assert.deepEqual(imported.data,s.data);});
test('legacy story/village/mystery data migrates without deleting old keys',()=>{const m=memory();m.setItem('galevein_story_done','1');m.setItem('galevein_hearthholm','3');m.setItem('galevein_myst','{"race":32.2}');const s=new SaveStore(m);assert.equal(s.data.profile.highestChapter,5);assert.equal(s.data.profile.mysteries.race,32.2);assert.equal(m.getItem('galevein_story_done'),'1');});
test('corrupted primary recovers the prior revision and retains a good backup',()=>{const m=memory(),s=new SaveStore(m);s.save(emptySave());s.save(fixture());m.setItem(SAVE_KEY,'broken');const recovered=new SaveStore(m);assert.equal(recovered.status,'recovered');assert.equal(recovered.data.checkpoint,null);recovered.save(fixture());assert.equal(decodeSave(m.getItem(BACKUP_KEY)).data.checkpoint,null);});
test('quota failure leaves durable primary unchanged',()=>{const m=memory(),s=new SaveStore(m);s.save(fixture());const raw=m.getItem(SAVE_KEY);const put=m.setItem;m.setItem=(k,v)=>{if(k===SAVE_KEY)throw Error('QuotaExceeded');put(k,v);};assert.throws(()=>s.save(emptySave()),/Quota/);assert.equal(m.getItem(SAVE_KEY),raw);});
test('another tab cannot silently overwrite a newer journey',()=>{const m=memory(),a=new SaveStore(m),b=new SaveStore(m);a.save(fixture());assert.throws(()=>b.save(emptySave()),SaveConflict);assert.equal(decodeSave(m.getItem(SAVE_KEY)).data.profile.scales,26);});
test('future saves cannot be silently replaced by an old client',()=>{const m=memory();const payload=JSON.stringify({...emptySave(),version:2});m.setItem(SAVE_KEY,JSON.stringify({format:'galevein-save',revision:7,payload,checksum:checksum(payload)}));m.setItem(BACKUP_KEY,encodeSave(emptySave()));const s=new SaveStore(m);assert.equal(s.status,'newer-version');assert.throws(()=>s.save(emptySave()),/recovery/);});
test('malformed import, negative currency, invalid health and invalid tutorial are rejected',()=>{const s=new SaveStore(memory());s.save(fixture());const before=s.export();assert.throws(()=>s.import('{bad'));for(const mutate of [s=>s.profile.scales=-1,s=>s.checkpoint.state.hp=Infinity,s=>s.checkpoint.tutorial=[false,false,false],s=>s.checkpoint.raid.wave=4,s=>s.checkpoint.dragon.position=[NaN,0,0]]){const v=fixture();mutate(v);assert.throws(()=>validateSave(v));}assert.equal(s.export(),before);});
test('unavailable browser storage has a usable in-memory starting profile',()=>{const s=new SaveStore({getItem(){throw Error('denied');}});assert.equal(s.status,'unavailable');assert.deepEqual(s.data,emptySave());});
test('checksum catches accidental payload edits',()=>{assert.throws(()=>decodeSave(encodeSave(fixture()).replace('stormcrest','voltspine')),/damaged/);});
test('unknown fields never enter the shared save model',()=>{const v=fixture();v.admin=true;v.profile.token='secret';v.checkpoint.dragon.mesh={};const clean=validateSave(v);assert.equal(clean.admin,undefined);assert.equal(clean.profile.token,undefined);assert.equal(clean.checkpoint.dragon.mesh,undefined);});
test('sync serializes writes and coalesces changes while a request is in flight',async()=>{const requests=[];let release;const client=new SaveSync({fetcher:async(_,options)=>{requests.push(JSON.parse(options.body));if(requests.length===1)await new Promise(r=>release=r);return {ok:true,status:200,json:async()=>({revision:requests.length})};}});client.connected=true;client.enqueue(emptySave());client.enqueue(fixture());release();while(client.running)await new Promise(r=>setImmediate(r));assert.equal(requests.length,2);assert.equal(requests[1].revision,1);assert.equal(requests[1].save.profile.scales,26);});
test('sync conflicts stop automatic uploads and require an explicit choice',async()=>{let writes=0;const client=new SaveSync({fetcher:async()=>{writes++;return {ok:false,status:409,json:async()=>({revision:8,save:fixture()})};}});client.connected=true;client.enqueue(emptySave());while(client.running)await new Promise(r=>setImmediate(r));client.enqueue(emptySave());assert.equal(writes,1);assert.equal(client.conflict.revision,8);const remote=client.resolveConflict(false);assert.equal(remote.profile.scales,26);assert.equal(client.pending,null);});
